######################################################################
# Automatically generated by qmake (3.0) ?? ?? 22 11:04:26 2013
######################################################################

QT += widgets
QT += printsupport
TEMPLATE = app
TARGET = Painter
INCLUDEPATH += .

# Input
HEADERS += colorbox.h paintarea.h painter.h resizedialog.h
FORMS += painter.ui resizedialog.ui
SOURCES += colorbox.cpp main.cpp paintarea.cpp painter.cpp resizedialog.cpp
RESOURCES += Image.qrc
